### ISSUE TITLE
Does the library continue to be updated

### ISSUE THREAD

**Issue by Shuo-Mr** [flyskywhy/react-native-uvc-camera#3]
This is a good library. It fills in the situation that react camera cannot connect to USB. However, this library seems to be old. Many supporting libraries have been updated. I now use react camera V3, but many of its dependencies are fixed, which makes it impossible for me to use the library.
For example, for the react native version, I use 0.63.0. It seems that the library needs version 0.51.0?

I am in urgent need of this function, and I am willing to study the project. Can you give me some directions, such as how to combine react camera with uvccamera? For those who don't know much about native development, it's really hard。

Thank!

**Comment by flyskywhy** [comment]
I'm glad for your appreciation.
I don't have a USB type-c camera on my hand, so I can't develop this repo to upgrade to 0.63.2 for now, only give you some directions :stuck_out_tongue_closed_eyes: 

I divided the steps of combining react camera with uvccamera into just several git commits, so you can study them especially the first 7 commit on master branch e.g. https://github.com/flyskywhy/react-native-uvc-camera/commit/f21ae94bf1872943b15723427139ee7ccb04f3ca

**Comment by Shuo-Mr** [comment]
OK, I'm going to have a look tonight. I have an idea here. React camera can't recognize the camera identifier of USB device, but usbcamera has the step of opening USB device. Then, can racact camera recognize the ID number of USB camera when opening USB device? In fact, I don't use a type-C camera. The device is an Android 6.0 tablet, but the libraries developed are relatively new, so I can't use it.

**Comment by Shuo-Mr** [comment]
I just saw the submission fragment you mentioned. It seems that they are all about introducing react native camera. What about uvccamera? In addition, the sample library example can not run. When installing the dependency, it will be blocked directly. When installing, you will be prompted to log in to GitHub account. After login, it will be stuck. It seems that some branches of the library are needed in the dependency.

**Comment by Shuo-Mr** [comment]
Hi, here I am. I read some source codes again. It seems that the combination only uses the shell of react native uvccamera to encapsulate uvccamera. In other words, it is not recognized by Android camera API after creating USB connection, which makes me feel frustrated.

**Comment by flyskywhy** [comment]
> I just saw the submission fragment you mentioned. It seems that they are all about introducing react native camera. What about uvccamera? In addition, the sample library example can not run. When installing the dependency, it will be blocked directly. When installing, you will be prompted to log in to GitHub account. After login, it will be stuck. It seems that some branches of the library are needed in the dependency.

Please

    npm uninstall react-native-check-box

then

    npm install react-native-check-box@2.1.7
